### ISSUE TITLE
distributed tensorflow

### ISSUE THREAD

**Issue by ssetty** [ischlag/distributed-tensorflow-example#13]
Hello,

Thanks for your blog on 

https://ischlag.github.io/2016/06/12/async-distributed-tensorflow/

When I run your code - same processing happens occurs on both worker nodes. 20 Epocs run on both worker nodes.
Ideally with distributed processing we expect compute or data decomposition so that processing  completes fast.
What should I change in code for this to happen?

Regards

**Comment by ischlag** [comment]
The code example is about data parallelism. So the same "processing" is supposed to occur on different worker nodes but with different data.

**Comment by ssetty** [comment]
Thanks 
Regarding data parallelism - how does different set of data points flow to different workers?  Does tensor framework does this behind scenes? Any link or explanation for this?

From your code below are snapshots from worker1 and worker2  (assume 2 workers)

We see at times different steps sometimes they overlap is it because of  asynchronous update of global variable?

If data parallelism happens then single worker should take more time compared to 2 workers? But actually single worker takes lesser time. Is it because  we need more intensive time consuming operations?

Snapshot 2 workers
**worker1**
Step: 21746,  Epoch: 20,  Batch: 300 of 550,  Cost: 2.4953,  AvgTime: 58.15ms
Step: 21846,  Epoch: 20,  Batch: 400 of 550,  Cost: 2.0955,  AvgTime: 5.82ms
Step: 21946,  Epoch: 20,  Batch: 500 of 550,  Cost: 2.2790,  AvgTime: 5.84ms
Step: 21996,  Epoch: 20,  Batch: 550 of 550,  Cost: 2.8113,  AvgTime: 2.82ms
Test-Accuracy: 0.42
Total Time: 110.26s
Final Cost: 2.8113
Done	

**worker2**  
Step: 21255,  Epoch: 20,  Batch: 100 of 550,  Cost: 2.4677,  AvgTime: 8.28ms
Step: 21355,  Epoch: 20,  Batch: 200 of 550,  Cost: 2.6989,  AvgTime: 5.50ms
Step: 21455,  Epoch: 20,  Batch: 300 of 550,  Cost: 2.3517,  AvgTime: 5.44ms
Step: 21555,  Epoch: 20,  Batch: 400 of 550,  Cost: 2.8017,  AvgTime: 5.72ms
Step: 21655,  Epoch: 20,  Batch: 500 of 550,  Cost: 2.2150,  AvgTime: 5.78ms
Step: 21705,  Epoch: 20,  Batch: 550 of 550,  Cost: 2.3954,  AvgTime: 2.70ms
Test-Accuracy: 0.42
Total Time: 103.99s
Final Cost: 2.3954
done


**Single worker**
Step: 10450,  Epoch: 19,  Batch: 550 of 550,  Cost: 3.8549,  AvgTime: 2.80ms
Step: 10550,  Epoch: 20,  Batch: 100 of 550,  Cost: 3.5690,  AvgTime: 6.50ms
Step: 10650,  Epoch: 20,  Batch: 200 of 550,  Cost: 3.4315,  AvgTime: 5.74ms
Step: 10750,  Epoch: 20,  Batch: 300 of 550,  Cost: 3.6123,  AvgTime: 5.50ms
Step: 10850,  Epoch: 20,  Batch: 400 of 550,  Cost: 3.3177,  AvgTime: 5.48ms
Step: 10950,  Epoch: 20,  Batch: 500 of 550,  Cost: 4.0169,  AvgTime: 5.44ms
Step: 11000,  Epoch: 20,  Batch: 550 of 550,  Cost: 3.5098,  AvgTime: 2.70ms
Test-Accuracy: 0.28
Total Time: 63.32s
Final Cost: 3.5098
done


Thanks

**Comment by ischlag** [comment]
> Thanks
> Regarding data parallelism - how does different set of data points flow to different workers? Does tensor framework does this behind scenes? Any link or explanation for this?
https://www.tensorflow.org/deploy/distributed
I think every worker generates its own data.

> From your code below are snapshots from worker1 and worker2 (assume 2 workers)
> 
> We see at times different steps sometimes they overlap is it because of asynchronous update of global variable?
I think that is because the variable is local to the machine. Not sure though.
> If data parallelism happens then single worker should take more time compared to 2 workers? But actually single worker takes lesser time. Is it because we need more intensive time consuming operations?
More workers need more time to initialize. Also, data parallelism doesn't necessarily mean that your training is double the speed. I guess I can't help you more as I have not looked at this since back then. Maybe you want to check the official documentation (see link above)

**Comment by ssetty** [comment]
Thanks for answers.
Tensorflow documentation does not clearly mention about data parallelism(as you have stated),
In my case I need to prove by adding more workers training time reduces - that is reason distributed tensorflow came into existence. 

Regards
