### ISSUE TITLE
Total number of batches in training

### ISSUE THREAD

**Issue by Mylak1995** [ischlag/distributed-tensorflow-example#15]
How does the example code ensure that each worker gets its own, unique batch at given time? It seems to me mnist.train.next_batch is ran locally in each worker, so they essentially get the same batches. I.e. for two workers, golbal_step=1 and global_step=2 is essentially training on the same batch.

**Comment by ischlag** [comment]
Your first statement is right but by default next_batch is shuffle=True which ensure that different batches are drawn from the individual workers on the same global step.
