### ISSUE TITLE
Hung on prepare_or_wait_for_session

### ISSUE THREAD

**Issue by speedcell4** [ischlag/distributed-tensorflow-example#4]
I changed the host URLs and tried your code but it hung on `prepare_or_wait_for_session`. 

Tensorflow v0.12
Python v3.5.2

**Comment by speedcell4** [comment]
this is on PS

```[basil301-(~)] python3 example.py --job_name="ps" --task_index=0
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:197] Initialize GrpcChannelCache for job ps -> {0 -> localhost:2222}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:197] Initialize GrpcChannelCache for job worker -> {0 -> basil302:2222, 1 -> basil303:2222, 2 -> basil304:2222}
I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:211] Started server with target: grpc://localhost:2222
Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
```

**Comment by speedcell4** [comment]
this is on worker

```[basil304-(~)] python3 example.py --job_name="worker" --task_index=2
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:197] Initialize GrpcChannelCache for job ps -> {0 -> basil301:2222}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:197] Initialize GrpcChannelCache for job worker -> {0 -> basil302:2222, 1 -> basil303:2222, 2 -> localhost:2222}
I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:211] Started server with target: grpc://localhost:2222
Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
WARNING:tensorflow:From example.py:125 in <module>.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
Variables initialized ...
```

**Comment by speedcell4** [comment]
after `Variables initialized ...` it just got stuck

**Comment by ischlag** [comment]
the example code only works for 3 workers and 1 parameter server. If I remember correctly, the workers ps will not send anything to the workers until all 3 are online. Is this the problem in your case?

If it is, you just have to remove the two workers from the cluster definition

**Comment by speedcell4** [comment]
No, I used three workers while only pasted one of them at here

**Comment by ischlag** [comment]
Well, this was made for TensorFlow 0.8.0. Maybe something has changed. Unfortunately, I currently don't have several machines at my disposal. Check the official distributed TensorFlow howto. Please let me know if you find a solution.

**Comment by guotong1988** [comment]
I can run it at v0.12.
But I don't know your reason.

**Comment by guotong1988** [comment]
I think this is the reason https://github.com/tensorflow/tensorflow/blob/r0.11/tensorflow/tools/dist_test/python/mnist_replica.py#L208
So the wrong place is ` --task_index=2`

**Comment by marchezinixd** [comment]
Having the same issue, when i use 1 computer running both PS and Workers it works, but when i use 2 computers the main one, with ps and worker run the whole code, the one with just the worker stops in "Variables initialized ...".

**Comment by marchezinixd** [comment]
@speedcell4 Check if you have installed the GRPC in all computers, it is necessary to have it in your computer, it is a missing information in the TF documentation. 
When i installed, it made the code fully work when using only one computer and made the main computer (running ps and worker) work when using 2+ computers, the others are still not working.
I`m still trying, i`ll post if i find a solution.

**Comment by speedcell4** [comment]
@marchezinixd Thank you so much!!! That is the point!!! I got all the 3 workers and PS run well by just installing GRPC

**Comment by marchezinixd** [comment]
Don`t close it please, i still have the problem when running in more then one PC.

**Comment by marchezinixd** [comment]
It's working now.
I recommend for people having trouble installing grpcio-tools and testing GRPC before running this example, both windows and ubuntu:
python -m pip install grpcio 
python -m pip install grpcio-tools

more information in:
http://www.grpc.io/docs/quickstart/python.html#download-the-example

thanks @speedcell4 you can close it now if you want.
