### ISSUE TITLE
Is this example be defined as data parallel or model parallel?

### ISSUE THREAD

**Issue by guotong1988** [ischlag/distributed-tensorflow-example#8]
Thanks @ischlag

**Comment by marchezinixd** [comment]
Almost sure it is model parallel, aparently it run the whole model everytime in all devices. I got to this conclusion, because it gave me the results in one worker while the other was stuck.

**Comment by ischlag** [comment]
No it is Data parallelism. Here you can read the blog post related to this source code: http://ischlag.github.io/2016/06/12/async-distributed-tensorflow/

Quote: "share all the model parameters across all workers while parallelising data and gradient updates"
